name: Create PR on PUSH to PRERELEASE branch

on:
  push:
    branches:
      - 'prerelease**'


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: validate inputs
        run: |
          [[ "$GITHUB_REF" =~ ^refs\/heads\/pre[a-z]+__[a-zA-Z0-9\_]+__[a-zA-Z0-9\_]+$ ]] && echo "branch name matches validation" || (echo "Invalid branch name, must be `prerelease__PROJECT_NAME__ENVIRONMENT`" && exit 1)

      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          ref: main
      - run: |
          BRANCH_NAME=$(echo $GITHUB_REF | sed -E "s/refs\/heads\/pre([a-z]+__[a-zA-Z0-9\_]+__[a-zA-Z0-9\_]+)/\1/" )
          env 
          git checkout -b $BRANCH_NAME 
          git push -u origin $BRANCH_NAME 
          echo "will this fail?"